port: 3000

auth:
  domain: https://tyvoid.auth0.com/
  jwksUrl: https://tyvoid.auth0.com/.well-known/jwks.json

services:
  - name: images
    url: http://localhost:3100
  - name: recipes
    url: http://localhost:3101

routes:
  - path: /recipes/.*
    service: recipes
    optionalAuth: true
  - path: /images/.*
    service: images
    optionalAuth: false # DEFAULT
    stripPrefix: "" # DEFAULT
