port: 3000
auth:
  domain: https://tyvoid.auth0.com/
  jwksUrl: https://tyvoid.auth0.com/.well-known/jwks.json

services:
  - name: images
    url: http://localhost:3100
  - name: recipes
    url: http://localhost:3101

routes:
  - path: /recipes/.*
    service: recipes
    authRequired: false
  - path: /images/.*
    service: images
    authRequired: true # DEFAULT
    stripPrefix: "" # DEFAULT
