port: 3000

services:
  - name: images
    url: http://localhost:3100
  - name: recipes
    url: http://localhost:3101

routes:
  - path: /recipes/.*
    service: recipes
    optionalAuth: true
  - path: /images/.*
    service: images
    optionalAuth: false # DEFAULT
    stripPrefix: "" # DEFAULT

plugins:
  # - path: lib/sample.so
  - path: lib/head_block.so
    settings:
      inbound:
        - X-Some
      outbound:
        - X-UserId
  - path: lib/jwt.so
    settings:
      domain: https://my.auth0.com/
      jwksUrl: https://my.auth0.com/.well-known/jwks.json
